### ISSUE TITLE
[BUG] After 9999th line, the line numbers are overlapping and incorrectly displayed

### ISSUE THREAD

**Issue by tomaserben** [atularen/ngx-monaco-editor#251]
![bug](https://user-images.githubusercontent.com/79214674/155319847-607b7c91-b655-4c2c-9ed8-89f339961561.png)

**Comment by SuperManito** [comment]
```css
.monaco-editor,
.monaco-diff-editor {
  .margin-view-overlays .line-numbers {
    white-space: nowrap;
  }
}
```
