### ISSUE TITLE
Styles are not applied

### ISSUE THREAD

**Issue by DevidCIC** [atularen/ngx-monaco-editor#53]
I want to change the color of the line numbers to gray. In [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html) the example below is working. So what am I doing wrong ? Why is my style not applied ?

```scss
.monaco-editor.vs .line-numbers {
    color: grey;
}
```

```html
<ngx-monaco-editor [ngModel]="text | async" (ngModelChange)="text.next($event)"
                   (onInit)="onEditorInit($event)" [options]="editorOptions"
                   class="monaco-editor"></ngx-monaco-editor>
```
